# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.7" #commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install -r ./application/requirements.txt
stages:
  - deploy

# define the jobs in deploy stage

deploy:
  stage: deploy
  script:
    - python ./application/bot.py


